title: Chris' Website
description: > # this means to ignore newlines until "baseurl:"
  Some things that I am proud of, but mostly navel gazing, still-forming ideas, and shouting into the void. Just trying to learn and grow as much as I can
permalink: ':title/'
#baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ctnle.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Chris Le # add your name
author-img: profile_pic.jpg # add your photo
about-author:  Some things that I am proud of, but mostly navel gazing, still-forming ideas, and shouting into the void. Just trying to learn and grow as much as I can # add description
social-twitter: ChristopherTNLe # add your Twitter handle
social-github: ctnle # add your Github handle
social-email: cle7@jh.edu add your Email address

# Disqus
#discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
